spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:profile-service-db}?createDatabaseIfNotExist=true
    username: ${DB_USER:devuser}
    password: ${DB_PASS:devuser}
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  oauth2:
    client:
      clientId: profile-service
      clientSecret: profile-service
      accessTokenUri: ${AUTH_SERVER:http://localhost:9191}/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: ${AUTH_SERVER:http://localhost:9191}/users/current
